excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Carthage

disabled_rules:
  - identifier_name
  # preventing us to have _ in the type name
  - type_name
  - force_try
  - force_cast
  # useful for nested decodable and coding keys
  - nesting

opt_in_rules:
#performance:
  - empty_string
  - first_where
  - contains_over_first_not_nil
  - sorted_first_last
#lint:
  - overridden_super_call
  - prohibited_super_call
  - yoda_condition
#idiomatic:
  - redundant_nil_coalescing
  - fatal_error_message
  - nimble_operator
  - joined_default_parameter
#style:
  - closure_spacing
  - empty_count
  - large_tuple
  - cyclomatic_complexity
  - line_length
  - file_length
  - function_parameter_count
  - function_body_length
  - vertical_parameter_alignment_on_call
  - implicit_return
  - literal_expression_end_indentation

colon:
  apply_to_dictionaries: false

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

vertical_whitespace:
  max_empty_lines: 2

function_body_length:
  warning: 80

function_parameter_count:
  warning: 5

line_length:
  warning: 160

file_length:
  warning: 500  
