language: objective-c
osx_image: xcode10
# xcode_project: Scuba.xcodeproj
# xcode_scheme: Tests
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X

script:
  - xcodebuild test -project Scuba.xcodeproj -scheme Scuba -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination "platform=iOS Simulator,OS=12.0,name=iPhone X"
  - xctool -project Scuba.xcodeproj -scheme Scuba -sdk iphonesimulator run-tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
